In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [2]:
data = pd.read_csv("Hackathon_train.csv")
data

dates  Factor A  Factor B  Factor C  Factor D  Factor E  \
0       1700-01-01    502.52    498.78    493.98     947.6    505.24   
1       1700-01-02    503.33    495.09    496.93     928.6    506.21   
2       1700-01-03    500.62    493.71    504.75     935.5    505.51   
3       1700-01-04    502.08    492.98    502.20     923.5    505.25   
4       1700-01-05    502.81    493.23    499.57     918.1    504.86   
...            ...       ...       ...       ...       ...       ...   
161763  2142-11-23  10499.99  10499.99  10499.99  100499.9   1499.99   
161764  2142-11-24  10499.99  10499.99  10499.99  100499.9   1499.99   
161765  2142-11-25  10499.99  10499.99  10499.99  100499.9   1499.99   
161766  2142-11-26  10499.99  10499.99  10499.99  100499.9   1499.99   
161767  2142-11-27  10499.99  10499.99  10499.99  100499.9   1499.99   

          Factor F  Factor G  Factor H  Factor I  Factor J  Factor K  \
0          79050.0    502.10    502.73    630.41    496.60    508.95   
1          31082.0    502.28    501.96    630.61    496.76    508.97   
2          19375.0    502.09    499.17    630.81    496.91    508.99   
3          22010.0    501.88    500.43    631.01    497.06    509.01   
4          26533.0    501.70    501.46    631.21    497.21    509.03   
...            ...       ...       ...       ...       ...       ...   
161763  10000500.0    599.99   1499.99  10499.99  10499.99  10499.99   
161764  10000500.0    599.99   1499.99  10499.99  10499.99  10499.99   
161765  10000500.0    599.99   1499.99  10499.99  10499.99  10499.99   
161766  10000500.0    599.99   1499.99  10499.99  10499.99  10499.99   
161767  10000500.0    599.99   1499.99  10499.99  10499.99  10499.99   

        Factor L  Factor M  Factor N  TGD Consultancy Share price  \
0         512.01    499.20    501.94                        519.0   
1         512.45    500.14    501.51                        518.0   
2         513.31    499.96    501.00                        523.0   
3         513.49    500.05    501.04                        522.0   
4         513.59    500.31    501.10                        522.0   
...          ...       ...       ...                          ...   
161763  10499.99  10499.99  10499.99                        498.0   
161764  10499.99  10499.99  10499.99                        502.0   
161765  10499.99  10499.99  10499.99                        508.0   
161766  10499.99  10499.99  10499.99                        507.0   
161767  10499.99  10499.99  10499.99                        499.0   

        TGD Automobiles Share price  TGD Power Share price  
0                             420.0                  507.0  
1                             420.0                  507.0  
2                             437.0                  522.0  
3                             437.0                  522.0  
4                             437.0                  522.0  
...                             ...                    ...  
161763                        420.0                  507.0  
161764                        420.0                  507.0  
161765                        420.0                  507.0  
161766                        420.0                  507.0  
161767                        420.0                  507.0  

[161768 rows x 18 columns]

In [3]:
consultancy_data = data[['Factor A', 'Factor B', 'Factor C', 'Factor D', 'Factor E', 'Factor F', 'Factor G', 
                        'Factor H', 'Factor I', 'Factor J', 'Factor K', 'Factor L', 'Factor M', 'Factor N', 
                        'TGD Power Share price','TGD Automobiles Share price','TGD Consultancy Share price']]
automobiles_data = data[['Factor A', 'Factor B', 'Factor C', 'Factor D', 'Factor E',
                       'Factor F', 'Factor G', 'Factor H', 'Factor I', 'Factor J', 'Factor K',
                       'Factor L', 'Factor M', 'Factor N','TGD Automobiles Share price']]
power_data = data[['Factor A', 'Factor B', 'Factor C', 'Factor D', 'Factor E',
                   'Factor F', 'Factor G', 'Factor H', 'Factor I', 'Factor J', 'Factor K',
                   'Factor L', 'Factor M', 'Factor N','TGD Power Share price']]

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [7]:
x = data.iloc[:,1:15]
scaler1 = MinMaxScaler()
x_scaled = scaler1.fit_transform(x)
y_consult = consultancy_data.iloc[:,-1]
y_auto = automobiles_data.iloc[:,-1]
y_power = power_data.iloc[:,-1]

In [6]:
from tensorflow.keras.optimizers.experimental import Adagrad

In [7]:
model2 = Sequential([tf.keras.Input(shape=x_scaled.shape[1]),
                    Dense(units=350, kernel_initializer='normal', activation='relu', name = 'layer1'),
                    Dense(units=256, kernel_initializer='normal', activation='relu', name = 'layer2'),
                    Dense(units=125, kernel_initializer='normal', activation='relu', name = 'layer3'),
                    Dense(units=1, kernel_initializer='normal', activation = 'linear', name = 'output_layer')])
model2.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 350)               5250      
                                                                 
 layer2 (Dense)              (None, 256)               89856     
                                                                 
 layer3 (Dense)              (None, 125)               32125     
                                                                 
 output_layer (Dense)        (None, 1)                 126       
                                                                 
Total params: 127,357
Trainable params: 127,357
Non-trainable params: 0
_________________________________________________________________


In [8]:
model2.compile(optimizer=Adam(0.001), loss=tf.keras.losses.MeanSquaredError())
history2 = model2.fit(x_scaled, y_auto, epochs = 25, batch_size = 60)

Epoch 1/25
2697/2697 [==============================] - 7s 2ms/step - loss: 4361.4888
Epoch 2/25
2697/2697 [==============================] - 7s 3ms/step - loss: 195.9503
Epoch 3/25
2697/2697 [==============================] - 7s 2ms/step - loss: 197.6594
Epoch 4/25
2697/2697 [==============================] - 7s 2ms/step - loss: 197.2743
Epoch 5/25
2697/2697 [==============================] - 7s 3ms/step - loss: 195.6350
Epoch 6/25
2697/2697 [==============================] - 6s 2ms/step - loss: 196.7819
Epoch 7/25
2697/2697 [==============================] - 7s 3ms/step - loss: 196.7518
Epoch 8/25
2697/2697 [==============================] - 6s 2ms/step - loss: 195.6605
Epoch 9/25
2697/2697 [==============================] - 7s 3ms/step - loss: 195.5666
Epoch 10/25
2697/2697 [==============================] - 7s 3ms/step - loss: 195.6946
Epoch 11/25
2697/2697 [==============================] - 7s 3ms/step - loss: 195.7561
Epoch 12/25
2697/2697 [==============================] - 8s 3m

In [9]:
model3 = Sequential([tf.keras.Input(shape=x_scaled.shape[1]),
                    Dense(units=350, kernel_initializer='normal', activation='relu', name = 'layer1'),
                    Dense(units=256, kernel_initializer='normal', activation='relu', name = 'layer2'),
                    Dense(units=125, kernel_initializer='normal', activation='relu', name = 'layer3'),
                    Dense(units=1, kernel_initializer='normal', activation = 'linear', name = 'output_layer')])
model3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 350)               5250      
                                                                 
 layer2 (Dense)              (None, 256)               89856     
                                                                 
 layer3 (Dense)              (None, 125)               32125     
                                                                 
 output_layer (Dense)        (None, 1)                 126       
                                                                 
Total params: 127,357
Trainable params: 127,357
Non-trainable params: 0
_________________________________________________________________


In [10]:
model3.compile(optimizer=Adam(0.001), loss=tf.keras.losses.MeanSquaredError())
history3 = model3.fit(x_scaled, y_auto, epochs = 25, batch_size = 60)

Epoch 1/25
2697/2697 [==============================] - 8s 3ms/step - loss: 4481.2520
Epoch 2/25
2697/2697 [==============================] - 6s 2ms/step - loss: 196.2263
Epoch 3/25
2697/2697 [==============================] - 7s 3ms/step - loss: 197.3365
Epoch 4/25
2697/2697 [==============================] - 6s 2ms/step - loss: 195.7261
Epoch 5/25
2697/2697 [==============================] - 7s 2ms/step - loss: 196.2657
Epoch 6/25
2697/2697 [==============================] - 7s 3ms/step - loss: 197.2148
Epoch 7/25
2697/2697 [==============================] - 7s 3ms/step - loss: 196.4949
Epoch 8/25
2697/2697 [==============================] - 8s 3ms/step - loss: 195.6455
Epoch 9/25
2697/2697 [==============================] - 7s 2ms/step - loss: 195.5949
Epoch 10/25
2697/2697 [==============================] - 8s 3ms/step - loss: 195.8254
Epoch 11/25
2697/2697 [==============================] - 6s 2ms/step - loss: 195.9885
Epoch 12/25
2697/2697 [==============================] - 7s 3m

In [11]:
x_consult = consultancy_data.iloc[:,:15]
scaler2 = MinMaxScaler()
x_consult_scaled = scaler2.fit_transform(x_consult)
x_consult_scaled

array([[4.43140141e-03, 3.33443950e-03, 4.31073514e-03, ...,
        8.67178782e-04, 1.01816104e-03, 1.75000000e-02],
       [4.51206287e-03, 2.96671440e-03, 4.60428705e-03, ...,
        9.61089848e-04, 9.75196438e-04, 1.75000000e-02],
       [4.24219551e-03, 2.82919119e-03, 5.38244838e-03, ...,
        9.43106878e-04, 9.24238428e-04, 5.50000000e-02],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.75000000e-02],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.75000000e-02],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.75000000e-02]])

In [25]:
x_consult

Factor A  Factor B  Factor C  Factor D  Factor E    Factor F  \
0         502.52    498.78    493.98     947.6    505.24     79050.0   
1         503.33    495.09    496.93     928.6    506.21     31082.0   
2         500.62    493.71    504.75     935.5    505.51     19375.0   
3         502.08    492.98    502.20     923.5    505.25     22010.0   
4         502.81    493.23    499.57     918.1    504.86     26533.0   
...          ...       ...       ...       ...       ...         ...   
161763  10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0   
161764  10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0   
161765  10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0   
161766  10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0   
161767  10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0   

        Factor G  Factor H  Factor I  Factor J  Factor K  Factor L  Factor M  \
0         502.10    502.73    630.41    496.60    508.95    512.01    499.20   
1         502.28    501.96    630.61    496.76    508.97    512.45    500.14   
2         502.09    499.17    630.81    496.91    508.99    513.31    499.96   
3         501.88    500.43    631.01    497.06    509.01    513.49    500.05   
4         501.70    501.46    631.21    497.21    509.03    513.59    500.31   
...          ...       ...       ...       ...       ...       ...       ...   
161763    599.99   1499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
161764    599.99   1499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
161765    599.99   1499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
161766    599.99   1499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
161767    599.99   1499.99  10499.99  10499.99  10499.99  10499.99  10499.99   

        Factor N  TGD Power Share price  
0         501.94                  507.0  
1         501.51                  507.0  
2         501.00                  522.0  
3         501.04                  522.0  
4         501.10                  522.0  
...          ...                    ...  
161763  10499.99                  507.0  
161764  10499.99                  507.0  
161765  10499.99                  507.0  
161766  10499.99                  507.0  
161767  10499.99                  507.0  

[161768 rows x 15 columns]

In [12]:
model1 = Sequential([tf.keras.Input(shape=x_consult_scaled.shape[1]),
                    Dense(units=350, kernel_initializer='normal', activation='relu', name = 'layer1'),
                    Dense(units=256, kernel_initializer='normal', activation='relu', name = 'layer2'),
                    Dense(units=125, kernel_initializer='normal', activation='relu', name = 'layer3'),
                    Dense(units=1, kernel_initializer='normal', activation = 'linear', name = 'output_layer')])
model1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 350)               5600      
                                                                 
 layer2 (Dense)              (None, 256)               89856     
                                                                 
 layer3 (Dense)              (None, 125)               32125     
                                                                 
 output_layer (Dense)        (None, 1)                 126       
                                                                 
Total params: 127,707
Trainable params: 127,707
Non-trainable params: 0
_________________________________________________________________


In [13]:
model1.compile(optimizer=Adam(0.001),
               loss = tf.keras.losses.MeanSquaredError())
history1 = model1.fit(x_consult_scaled, y_consult, epochs = 25, batch_size = 60)

Epoch 1/25
2697/2697 [==============================] - 8s 3ms/step - loss: 6639.2817
Epoch 2/25
2697/2697 [==============================] - 6s 2ms/step - loss: 251.6384
Epoch 3/25
2697/2697 [==============================] - 7s 3ms/step - loss: 251.3476
Epoch 4/25
2697/2697 [==============================] - 6s 2ms/step - loss: 252.3305
Epoch 5/25
2697/2697 [==============================] - 7s 3ms/step - loss: 250.2873
Epoch 6/25
2697/2697 [==============================] - 7s 2ms/step - loss: 248.3346
Epoch 7/25
2697/2697 [==============================] - 7s 2ms/step - loss: 248.9891
Epoch 8/25
2697/2697 [==============================] - 7s 3ms/step - loss: 249.4498
Epoch 9/25
2697/2697 [==============================] - 8s 3ms/step - loss: 247.3652
Epoch 10/25
2697/2697 [==============================] - 9s 3ms/step - loss: 249.2217
Epoch 11/25
2697/2697 [==============================] - 8s 3ms/step - loss: 248.3445
Epoch 12/25
2697/2697 [==============================] - 9s 3m

In [14]:
test_data = pd.read_csv('Hackathon_test.csv')
test_data = test_data.iloc[:,1:]
test_data_scaled = scaler1.transform(test_data)
test_data_scaled

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       ...,
       [4.36368561e-03, 3.90745286e-03, 5.42225203e-03, ...,
        1.02343701e-03, 7.12325428e-04, 8.45303470e-04],
       [3.82195924e-03, 3.97920410e-03, 4.95057879e-03, ...,
        1.02743872e-03, 7.74266769e-04, 9.85188205e-04],
       [3.87573355e-03, 4.14164093e-03, 4.49084665e-03, ...,
        9.61410522e-04, 8.03239332e-04, 9.56212081e-04]])

In [15]:
predict_auto = model2.predict(test_data_scaled)
predict_auto

938/938 [==============================] - 1s 1ms/step


array([[415.8962 ],
       [415.8962 ],
       [415.8962 ],
       ...,
       [415.29996],
       [415.57877],
       [415.34167]], dtype=float32)

In [16]:
predict_power = model3.predict(test_data_scaled)
predict_power

938/938 [==============================] - 1s 1ms/step


array([[415.8284 ],
       [415.8284 ],
       [415.8284 ],
       ...,
       [418.2971 ],
       [418.57443],
       [418.42795]], dtype=float32)

In [19]:
x_consult_test = pd.DataFrame(np.concatenate([test_data, predict_power], axis = 1))
x_consult_test

0         1         2         3        4           5       6   \
0      10499.99  10499.99  10499.99  100499.9  1499.99  10000500.0  599.99   
1      10499.99  10499.99  10499.99  100499.9  1499.99  10000500.0  599.99   
2      10499.99  10499.99  10499.99  100499.9  1499.99  10000500.0  599.99   
3      10499.99  10499.99  10499.99  100499.9  1499.99  10000500.0  599.99   
4        503.94    497.55    499.63     894.7   502.82     94705.0  500.88   
...         ...       ...       ...       ...      ...         ...     ...   
29995    500.82    506.68    500.90     893.7   504.21    233367.0  501.30   
29996    499.46    503.79    505.45     913.4   504.21    180508.0  501.44   
29997    501.84    504.53    505.15     903.9   503.90    193973.0  501.27   
29998    496.40    505.25    500.41     929.0   503.16    167564.0  501.16   
29999    496.94    506.88    495.79     895.7   503.98    159933.0  501.25   

            7         8         9         10        11        12        13  \
0      1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
1      1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
2      1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
3      1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99   
4       499.93    736.35    596.33    498.68    514.90    499.69    500.44   
...        ...       ...       ...       ...       ...       ...       ...   
29995   499.24    736.27    586.38    507.95    514.26    496.98    500.78   
29996   497.56    736.31    586.31    507.96    514.11    498.10    501.06   
29997   497.46    736.38    586.23    507.98    514.49    497.65    500.21   
29998   499.57    736.41    586.19    507.98    514.53    498.27    501.61   
29999   501.03    736.47    586.11    508.00    513.87    498.56    501.32   

               14  
0      415.828400  
1      415.828400  
2      415.828400  
3      415.828400  
4      417.940430  
...           ...  
29995  418.178650  
29996  418.584747  
29997  418.297089  
29998  418.574432  
29999  418.427948  

[30000 rows x 15 columns]

In [31]:
x_consult_test.rename(columns = {0:'Factor A', 1:'Factor B', 2:'Factor C', 3:'Factor D', 4:'Factor E', 5:'Factor F', 6:'Factor G', 
                        7:'Factor H', 8:'Factor I', 9:'Factor J', 10:'Factor K', 11:'Factor L', 12:'Factor M', 13:'Factor N', 
                        14:'TGD Power Share price'}, inplace=True)
test_scaled_consult = pd.DataFrame(scaler2.transform(x_consult_test))
test_scaled_consult.rename(columns = {0:'Factor A', 1:'Factor B', 2:'Factor C', 3:'Factor D', 4:'Factor E', 5:'Factor F', 6:'Factor G', 
                        7:'Factor H', 8:'Factor I', 9:'Factor J', 10:'Factor K', 11:'Factor L', 12:'Factor M', 13:'Factor N', 
                        14:'TGD Power Share price'}, inplace=True)
test_scaled_consult

Factor A  Factor B  Factor C  Factor D  Factor E  Factor F  Factor G  \
0      1.000000  1.000000  1.000000  1.000000   1.00000  1.000000  1.000000   
1      1.000000  1.000000  1.000000  1.000000   1.00000  1.000000  1.000000   
2      1.000000  1.000000  1.000000  1.000000   1.00000  1.000000  1.000000   
3      1.000000  1.000000  1.000000  1.000000   1.00000  1.000000  1.000000   
4      0.004573  0.003212  0.004873  0.001639   0.00275  0.009171  0.008503   
...         ...       ...       ...       ...       ...       ...       ...   
29995  0.004262  0.004122  0.004999  0.001629   0.00414  0.023041  0.012705   
29996  0.004127  0.003834  0.005452  0.001826   0.00414  0.017754  0.014106   
29997  0.004364  0.003907  0.005422  0.001731   0.00383  0.019101  0.012405   
29998  0.003822  0.003979  0.004951  0.001983   0.00309  0.016459  0.011305   
29999  0.003876  0.004142  0.004491  0.001649   0.00391  0.015696  0.012205   

       Factor H  Factor I  Factor J  Factor K  Factor L  Factor M  Factor N  \
0      1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
1      1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
2      1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
3      1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
4      0.034971  0.028698  0.040607  0.002666  0.001064  0.000916  0.000868   
...         ...       ...       ...       ...       ...       ...       ...   
29995  0.034305  0.028690  0.039643  0.003590  0.001000  0.000645  0.000902   
29996  0.032684  0.028694  0.039636  0.003591  0.000985  0.000757  0.000930   
29997  0.032587  0.028701  0.039629  0.003593  0.001023  0.000712  0.000845   
29998  0.034623  0.028704  0.039625  0.003593  0.001027  0.000774  0.000985   
29999  0.036032  0.028710  0.039617  0.003595  0.000961  0.000803  0.000956   

       TGD Power Share price  
0                  -0.210429  
1                  -0.210429  
2                  -0.210429  
3                  -0.210429  
4                  -0.205149  
...                      ...  
29995              -0.204553  
29996              -0.203538  
29997              -0.204257  
29998              -0.203564  
29999              -0.203930  

[30000 rows x 15 columns]

In [32]:
predict_consult = model1.predict(test_scaled_consult)
predict_consult

938/938 [==============================] - 1s 1ms/step


array([[447.8109],
       [447.8109],
       [447.8109],
       ...,
       [428.8366],
       [429.0959],
       [428.9776]], dtype=float32)

In [33]:
y_final = pd.DataFrame(predict_consult + predict_auto + predict_power)
y_final

0
0      1279.535522
1      1279.535522
2      1279.535522
3      1279.535522
4      1260.973389
...            ...
29995  1262.273926
29996  1263.314575
29997  1262.433716
29998  1263.249146
29999  1262.747192

[30000 rows x 1 columns]

In [5]:
forest = RandomForestRegressor()
scaler3 = MinMaxScaler()

In [6]:
y_forest = data['TGD Consultancy Share price'] + data['TGD Automobiles Share price']+ data['TGD Power Share price']
y_forest

0         1446.0
1         1445.0
2         1482.0
3         1481.0
4         1481.0
           ...  
161763    1425.0
161764    1429.0
161765    1435.0
161766    1434.0
161767    1426.0
Length: 161768, dtype: float64

In [9]:
x_forest_scaled = scaler3.fit_transform(x)
x_forest_scaled

array([[4.43140141e-03, 3.33443950e-03, 4.31073514e-03, ...,
        7.75331066e-04, 8.67178782e-04, 1.01816104e-03],
       [4.51206287e-03, 2.96671440e-03, 4.60428705e-03, ...,
        8.19349862e-04, 9.61089848e-04, 9.75196438e-04],
       [4.24219551e-03, 2.82919119e-03, 5.38244838e-03, ...,
        9.05386600e-04, 9.43106878e-04, 9.24238428e-04],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [10]:
forest.fit(x_forest_scaled, y_forest)

RandomForestRegressor()

In [13]:
test_data_forest = pd.read_csv('Hackathon_test.csv')
test_data_forest = test_data_forest.iloc[:,1:]
test_data_forest

Factor A  Factor B  Factor C  Factor D  Factor E    Factor F  Factor G  \
0      10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0    599.99   
1      10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0    599.99   
2      10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0    599.99   
3      10499.99  10499.99  10499.99  100499.9   1499.99  10000500.0    599.99   
4        503.94    497.55    499.63     894.7    502.82     94705.0    500.88   
...         ...       ...       ...       ...       ...         ...       ...   
29995    500.82    506.68    500.90     893.7    504.21    233367.0    501.30   
29996    499.46    503.79    505.45     913.4    504.21    180508.0    501.44   
29997    501.84    504.53    505.15     903.9    503.90    193973.0    501.27   
29998    496.40    505.25    500.41     929.0    503.16    167564.0    501.16   
29999    496.94    506.88    495.79     895.7    503.98    159933.0    501.25   

       Factor H  Factor I  Factor J  Factor K  Factor L  Factor M  Factor N  
0       1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99  
1       1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99  
2       1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99  
3       1499.99  10499.99  10499.99  10499.99  10499.99  10499.99  10499.99  
4        499.93    736.35    596.33    498.68    514.90    499.69    500.44  
...         ...       ...       ...       ...       ...       ...       ...  
29995    499.24    736.27    586.38    507.95    514.26    496.98    500.78  
29996    497.56    736.31    586.31    507.96    514.11    498.10    501.06  
29997    497.46    736.38    586.23    507.98    514.49    497.65    500.21  
29998    499.57    736.41    586.19    507.98    514.53    498.27    501.61  
29999    501.03    736.47    586.11    508.00    513.87    498.56    501.32  

[30000 rows x 14 columns]

In [14]:
test_data_forest_scaled = scaler3.transform(test_data_forest)
test_data_forest_scaled

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       ...,
       [4.36368561e-03, 3.90745286e-03, 5.42225203e-03, ...,
        1.02343701e-03, 7.12325428e-04, 8.45303470e-04],
       [3.82195924e-03, 3.97920410e-03, 4.95057879e-03, ...,
        1.02743872e-03, 7.74266769e-04, 9.85188205e-04],
       [3.87573355e-03, 4.14164093e-03, 4.49084665e-03, ...,
        9.61410522e-04, 8.03239332e-04, 9.56212081e-04]])

In [17]:
final_predictions_forest = pd.DataFrame(forest.predict(test_data_forest_scaled))
final_predictions_forest

0
0      1439.209419
1      1439.209419
2      1439.209419
3      1439.209419
4      1425.710000
...            ...
29995  1459.070000
29996  1434.430000
29997  1450.640000
29998  1442.190000
29999  1441.510000

[30000 rows x 1 columns]